# .github/workflows/assembla_doc_template.yml

name: Assembla Documento con Template

on:
  push:
    branches: [ main ]
    paths: 
      - 'docs/sezioni/**'
      - 'config.yml'
      - '.github/scripts/**'
      - '.github/workflows/**'

  pull_request:
    branches: [ main ]
    paths:
      - 'docs/sezioni/**'
      - 'config.yml'
      - '.github/scripts/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kjarosh/latex:2024.4-medium

    steps:
    - name: Install git
      run: apk add --no-cache git

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Debug .git presence immediately after checkout
      run: ls -la $GITHUB_WORKSPACE/.git

    - name: Install Python + deps
      run: |
        apk add --no-cache python3 py3-pip bash
        pip install --break-system-packages pyyaml python-liquid

    - name: Processa i template con Python
      run: python3 .github/scripts/process-template.py

    - name: Install Pandoc
      run: apk add --no-cache pandoc

    - name: Genera il PDF con Pandoc
      run: |
        pandoc progetto-completo.md -o progetto-completo.pdf \
          --pdf-engine=pdflatex \
          --variable geometry:margin=2cm \
          --variable fontsize=11pt \
          --variable documentclass=article \
          --variable lang=it

    - name: Debug check for .git
      run: ls -la $GITHUB_WORKSPACE/.git

    - name: Commit del documento assemblato
      working-directory: $GITHUB_WORKSPACE
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add progetto-completo.md progetto-completo.pdf debug-programmazione.json
        git diff --staged --quiet || git commit -m "Auto-aggiornamento documento con template [skip ci]"

    - name: Push delle modifiche
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
