# .github/workflows/assembla_doc_template.yml

name: Assembla Documento con Template

on:
  push:
    branches: [ main ]
    paths: 
      - 'docs/sezioni/**'
      - 'config.yml'
      - '.github/scripts/**'
      - '.github/workflows/**'

  pull_request:
    branches: [ main ]
    paths:
      - 'docs/sezioni/**'
      - 'config.yml'
      - '.github/scripts/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # --- Inizio Sezione Installazione Dipendenze ---
    - name: Installare dipendenze di sistema (LaTeX e Pandoc)
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          pandoc \
          texlive-latex-base \
          texlive-fonts-recommended \
          texlive-extra-utils \
          texlive-lang-italian

    - name: Setup Node.js v18
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Installare dipendenze Node.js (liquidjs, js-yaml)
      run: npm install liquidjs js-yaml

    # --- Fine Sezione Installazione Dipendenze ---
              
    - name: Processa i template con lo script Node.js
      run: node .github/scripts/process-templates.js

    - name: Genera il PDF con Pandoc
      run: |
        pandoc progetto-completo.md -o progetto-completo.pdf \
          --pdf-engine=pdflatex \
          --variable geometry:margin=2cm \
          --variable fontsize=11pt \
          --variable documentclass=article \
          --variable lang=it

    - name: Commit del documento assemblato
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add progetto-completo.md progetto-completo.pdf debug-programmazione.json
        git diff --staged --quiet || git commit -m "Auto-aggiornamento documento con template [skip ci]"
        
    - name: Push delle modifiche
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main